import { COUNTRIES, CURRENCIES, DEPENDENCY_LEVELS, MONTHS, TRI_HELP, opts, q } from "@/lib/questionnaire/builders";
import { activityOptions } from "@/lib/questionnaire/industries";
import type { Persistence, StepDefinition } from "@/lib/questionnaire/types";

const p = (table: string, column: string, note?: string): Persistence => ({ table, column, note });
const INPUT = "assessment_input_versions";

export const purposeStep: StepDefinition = {
  id: "purpose",
  number: 1,
  title: "Purpose and context",
  short: "Purpose",
  summary: "Why the assessment is being run and how much detail to collect.",
  why: "The purpose decides which questions appear. Level A is an initial screening. Level B adds the detail needed for a lender, insurer or site decision.",
  dimensions: ["context"],
  external: [],
  optional: false,
  sections: [
    {
      key: "purpose.main",
      title: "Assessment purpose",
      questions: [
        q({
          key: "purpose.goals",
          label: "What should this assessment help with?",
          help: "Choose all that apply. Choosing a new site adds the prospective-location step.",
          type: "multiselect",
          required: true,
          width: "full",
          dimensions: ["context"],
          validation: { minItems: 1 },
          options: opts([
            ["understand_current_risk", "Understand climate risk at current sites"],
            ["continuity_planning", "Plan business continuity and adaptation"],
            ["lender_review", "Prepare information for a lender or investor review"],
            ["insurance_review", "Review insurance cover"],
            ["supplier_review", "Review supplier dependence"],
            ["new_site", "Compare a new or prospective site"],
          ]),
          persistence: p(INPUT, "answers.purpose.goals"),
        }),
        q({
          key: "purpose.depth",
          label: "Assessment depth",
          type: "radio",
          required: true,
          width: "full",
          dimensions: ["context"],
          options: [
            { value: "A", label: "Initial screening (Level A)", help: "Core questions only. Enough for a first hazard and dependency screen." },
            { value: "B", label: "Advanced assessment (Level B)", help: "Adds assets, detailed financials, utility evidence and cost assumptions." },
          ],
          persistence: p(INPUT, "level"),
        }),
        q({
          key: "purpose.respondent_role",
          label: "Your role",
          type: "select",
          required: true,
          dimensions: ["governance"],
          options: opts([
            ["owner", "Owner or director"],
            ["finance", "Finance or accounts"],
            ["operations", "Operations or plant manager"],
            ["consultant", "External adviser completing on the business's behalf"],
            ["lender_analyst", "Lender or programme analyst"],
            ["other", "Other"],
          ]),
          persistence: p(INPUT, "answers.purpose.respondent_role"),
        }),
        q({
          key: "purpose.horizons",
          label: "Time horizons of interest",
          help: "Which horizons can be shown depends on the configured data sources. Projections are not forecasts.",
          type: "multiselect",
          dimensions: ["context"],
          options: opts([
            ["forecast_7d", "Current conditions and 7-day forecast"],
            ["historical", "Historical context, 1991–2020 climatology"],
            ["projection", "Long-term climate projections"],
          ]),
          persistence: p(INPUT, "answers.purpose.horizons"),
        }),
        q({
          key: "purpose.decision_date",
          label: "Date a decision depends on this",
          type: "date",
          level: "B",
          visibleWhen: { level: "B" },
          dimensions: ["context"],
          persistence: p(INPUT, "answers.purpose.decision_date"),
        }),
        q({
          key: "purpose.notes",
          label: "Anything the reviewer should know",
          type: "textarea",
          level: "B",
          width: "full",
          visibleWhen: { level: "B" },
          validation: { maxLength: 1500 },
          dimensions: ["context"],
          persistence: p(INPUT, "answers.purpose.notes"),
        }),
      ],
    },
  ],
};

export const profileStep: StepDefinition = {
  id: "profile",
  number: 2,
  title: "Identity, industry and operating profile",
  short: "Business profile",
  summary: "Who the business is, what it does and how it operates.",
  why: "Industry sets heat thresholds and which industry-specific questions are asked. Size and seasonality frame operational and financial sensitivity.",
  dimensions: ["context", "operational_sensitivity"],
  external: [],
  optional: false,
  sections: [
    {
      key: "profile.identity",
      title: "Identity",
      description: "Business details only. Personal identity numbers, bank credentials or card details are never requested.",
      questions: [
        q({ key: "profile.legal_name", label: "Registered business name", type: "text", required: true, material: true, validation: { maxLength: 160 }, dimensions: ["context"], persistence: p("businesses", "name") }),
        q({ key: "profile.trading_name", label: "Trading name", help: "If different from the registered name.", type: "text", validation: { maxLength: 160 }, dimensions: ["context"], persistence: p("businesses", "trading_name") }),
        q({
          key: "profile.legal_form",
          label: "Legal form",
          type: "select",
          dimensions: ["context"],
          options: opts([
            ["proprietorship", "Sole proprietorship"],
            ["partnership", "Partnership"],
            ["llp", "Limited liability partnership"],
            ["private_limited", "Private limited company"],
            ["public_limited", "Public limited company"],
            ["cooperative", "Cooperative"],
            ["other", "Other"],
          ]),
          persistence: p("businesses", "legal_type"),
        }),
        q({ key: "profile.registration_country", label: "Country of registration", type: "combobox", required: true, options: COUNTRIES, dimensions: ["context"], persistence: p("businesses", "registration_country") }),
        q({
          key: "profile.registration_identifier",
          label: "Business registration number",
          help: "Optional business identifier such as a company or enterprise registration number. Do not enter personal ID numbers.",
          type: "text",
          level: "B",
          visibleWhen: { level: "B" },
          sensitivity: "confidential",
          validation: { pattern: { regex: "^(?!\\d{12}$)[A-Za-z0-9/-]{4,30}$", message: "Use 4–30 letters, digits, slashes or hyphens. A 12-digit personal ID number is not accepted." } },
          dimensions: ["context"],
          persistence: p("businesses", "registration_identifier"),
        }),
      ],
    },
    {
      key: "profile.industry",
      title: "Industry and activity",
      questions: [
        q({
          key: "profile.activity",
          label: "Main activity",
          help: "Search by activity. The ISIC Rev.4 section is shown for each option.",
          type: "combobox",
          required: true,
          material: true,
          options: activityOptions(),
          dimensions: ["context", "operational_sensitivity", "hazard_exposure"],
          persistence: p("businesses", "sub_industry", "Activity key. businesses.industry stores the activity label."),
        }),
        q({ key: "profile.activity_description", label: "Products and services", type: "textarea", width: "full", validation: { maxLength: 1000 }, dimensions: ["context"], persistence: p("businesses", "products_services") }),
        q({ key: "profile.established_year", label: "Year established", type: "number", validation: { integer: true, min: 1800, max: new Date().getFullYear() }, dimensions: ["context"], persistence: p("businesses", "established_year") }),
        q({
          key: "profile.size_band",
          label: "Enterprise size",
          help: "As classified under your national MSME definition.",
          type: "select",
          required: true,
          dimensions: ["context", "financial_sensitivity"],
          options: opts([["micro", "Micro"], ["small", "Small"], ["medium", "Medium"], ["larger", "Larger than medium"], ["unknown", "Not sure"]]),
          persistence: p("businesses", "msme_size_band"),
        }),
        q({
          key: "profile.employee_band",
          label: "Employees",
          type: "select",
          required: true,
          dimensions: ["context", "operational_sensitivity"],
          options: opts([["1-9", "1–9"], ["10-49", "10–49"], ["50-249", "50–249"], ["250+", "250 or more"]]),
          persistence: p("businesses", "employee_band"),
        }),
        q({ key: "profile.employee_count", label: "Exact employee count", type: "number", level: "B", visibleWhen: { level: "B" }, validation: { integer: true, min: 0, max: 1000000 }, dimensions: ["context"], persistence: p("businesses", "employee_count") }),
      ],
    },
    {
      key: "profile.operations",
      title: "Operating pattern",
      questions: [
        q({
          key: "profile.customer_types",
          label: "Main customers",
          type: "multiselect",
          dimensions: ["context", "financial_sensitivity"],
          options: opts([["households", "Households"], ["businesses", "Other businesses"], ["government", "Government"], ["export", "Export customers"]]),
          persistence: p("businesses", "customer_types"),
        }),
        q({
          key: "profile.operating_days",
          label: "Operating days per week",
          type: "select",
          dimensions: ["operational_sensitivity"],
          options: opts([["5", "5 days"], ["6", "6 days"], ["7", "7 days"], ["seasonal", "Seasonal or irregular"]]),
          persistence: p("businesses", "operating_model", "Combined with shift pattern."),
        }),
        q({
          key: "profile.shift_pattern",
          label: "Shift pattern",
          type: "select",
          level: "B",
          visibleWhen: { level: "B" },
          dimensions: ["operational_sensitivity"],
          options: opts([["single", "Single day shift"], ["two", "Two shifts"], ["continuous", "Continuous, 24 hours"]]),
          persistence: p("businesses", "operating_model", "Combined with operating days."),
        }),
        q({
          key: "profile.seasonality",
          label: "How seasonal is revenue?",
          type: "radio",
          dimensions: ["financial_sensitivity", "operational_sensitivity"],
          options: opts([["none", "Little or no seasonality"], ["moderate", "Moderate"], ["strong", "Strong peaks"]]),
          persistence: p("businesses", "seasonality"),
        }),
        q({
          key: "profile.peak_months",
          label: "Peak months",
          help: "Peaks that coincide with monsoon or heat months raise financial sensitivity to disruption.",
          type: "multiselect",
          width: "full",
          visibleWhen: { field: "profile.seasonality", in: ["moderate", "strong"] },
          options: MONTHS,
          dimensions: ["financial_sensitivity"],
          persistence: p("businesses", "seasonality", "Stored with the seasonality answer."),
        }),
      ],
    },
  ],
};

const SITE_TYPES = opts([
  ["head_office", "Head office"],
  ["shop", "Shop or showroom"],
  ["factory", "Factory or workshop"],
  ["warehouse", "Warehouse"],
  ["farm", "Farm"],
  ["processing", "Processing unit"],
  ["distribution", "Distribution centre"],
  ["other", "Other"],
]);

export const locationsStep: StepDefinition = {
  id: "locations",
  number: 3,
  title: "Operating locations",
  short: "Locations",
  summary: "Every site the business operates, with a confirmed map position.",
  why: "Hazard data is retrieved for each confirmed coordinate. Place-name geocoding is not rooftop accuracy, so each pin must be confirmed or accepted as lower precision.",
  dimensions: ["hazard_exposure", "operational_sensitivity"],
  external: ["Open-Meteo geocoding (place candidates)", "Open-Meteo forecast and ERA5 archive per site", "Sentinel-2 L2A catalogue search per site"],
  optional: false,
  sections: [
    {
      key: "sites",
      title: "Sites",
      description: "Add each operating site. Mark one as the primary site.",
      group: {
        key: "sites",
        label: "Operating sites",
        itemLabel: "Site",
        minItems: 1,
        maxItems: 12,
        level: "A",
        persistenceTable: "business_locations",
        questions: [
          q({ key: "label", label: "Site name", type: "text", required: true, validation: { maxLength: 120 }, dimensions: ["context"], persistence: p("business_locations", "label") }),
          q({ key: "site_type", label: "Site type", type: "select", required: true, material: true, options: SITE_TYPES, dimensions: ["operational_sensitivity"], persistence: p("business_locations", "site_type") }),
          q({ key: "is_primary", label: "Primary site", help: "The site analysed first; the AI reports describe this site.", type: "boolean", dimensions: ["context"], persistence: p("business_locations", "is_primary") }),
          q({ key: "address_line", label: "Street address", type: "text", width: "full", validation: { maxLength: 240 }, dimensions: ["hazard_exposure"], persistence: p("business_locations", "address_line") }),
          q({ key: "city", label: "City or town", type: "text", required: true, validation: { maxLength: 120 }, dimensions: ["hazard_exposure"], persistence: p("business_locations", "city") }),
          q({ key: "admin_area", label: "State or province", type: "text", validation: { maxLength: 120 }, dimensions: ["hazard_exposure"], persistence: p("business_locations", "admin_area") }),
          q({ key: "postal_code", label: "Postal code", type: "text", validation: { maxLength: 16 }, dimensions: ["hazard_exposure"], persistence: p("business_locations", "postal_code") }),
          q({ key: "country", label: "Country", type: "combobox", required: true, options: COUNTRIES, dimensions: ["hazard_exposure"], persistence: p("business_locations", "country") }),
          q({
            key: "point",
            label: "Map position",
            help: "Search for the town or locality, then adjust the coordinates to the site and confirm.",
            type: "geopoint",
            required: true,
            material: true,
            width: "full",
            dimensions: ["hazard_exposure"],
            persistence: p("business_locations", "latitude, longitude, geocoder_name, match_quality, user_confirmed, accepted_low_precision"),
          }),
          q({ key: "site_status", label: "Status", type: "select", required: true, options: opts([["active", "Operating"], ["planned", "Planned"], ["closed", "Closed"]]), dimensions: ["context"], persistence: p("business_locations", "site_status") }),
          q({ key: "tenure", label: "Tenure", type: "select", options: opts([["owned", "Owned"], ["leased", "Leased or rented"], ["shared", "Shared or co-located"], ["other", "Other"]]), dimensions: ["adaptive_capacity"], persistence: p("business_locations", "tenure") }),
          q({ key: "criticality", label: "Importance to the business", type: "select", required: true, material: true, options: opts([["critical", "Critical: the business stops without it"], ["high", "High"], ["medium", "Medium"], ["low", "Low"]]), dimensions: ["operational_sensitivity"], persistence: p("business_locations", "criticality") }),
          q({ key: "activity", label: "What happens at this site", type: "textarea", width: "full", validation: { maxLength: 600 }, dimensions: ["operational_sensitivity"], persistence: p("business_locations", "activity") }),
          q({
            key: "lowest_level",
            label: "Lowest level where stock or equipment is kept",
            type: "select",
            material: true,
            options: opts([["basement", "Basement"], ["ground", "Ground floor"], ["raised", "Raised plinth or upper floor"], ["mixed", "Mixed"], ["unknown", "Not sure"]]),
            dimensions: ["hazard_exposure", "adaptive_capacity"],
            persistence: p("business_locations", "lowest_occupied_level"),
          }),
          q({ key: "building_area", label: "Built-up area", type: "number", unit: "m²", level: "B", visibleWhen: { level: "B" }, validation: { min: 0, max: 10000000 }, dimensions: ["site_feasibility"], persistence: p("business_locations", "building_area") }),
          q({ key: "land_area", label: "Land area", type: "number", unit: "m²", level: "B", visibleWhen: { level: "B" }, validation: { min: 0, max: 100000000 }, dimensions: ["site_feasibility"], persistence: p("business_locations", "land_area") }),
          q({ key: "staff_count", label: "Staff working at this site", type: "number", level: "B", visibleWhen: { level: "B" }, validation: { integer: true, min: 0, max: 1000000 }, dimensions: ["operational_sensitivity"], persistence: p("business_locations", "staff_count") }),
          q({ key: "opening_hours", label: "Opening hours", type: "text", level: "B", visibleWhen: { level: "B" }, validation: { maxLength: 120 }, dimensions: ["operational_sensitivity"], persistence: p("business_locations", "opening_hours") }),
        ],
      },
    },
  ],
};

export const prospectsStep: StepDefinition = {
  id: "prospects",
  number: 4,
  title: "Prospective locations and expansion",
  short: "Prospective sites",
  summary: "Candidate sites under consideration and how they should be compared.",
  why: "Candidate sites are screened with the same hazard sources as operating sites. Budgets come only from you; no market price is added.",
  dimensions: ["site_feasibility", "hazard_exposure"],
  external: ["Open-Meteo geocoding", "Open-Meteo forecast and archive per candidate"],
  optional: true,
  sections: [
    {
      key: "prospects.intro",
      title: "Expansion plans",
      questions: [
        q({
          key: "prospects.planning",
          label: "Are you considering a new or additional site?",
          type: "radio",
          required: true,
          dimensions: ["site_feasibility"],
          options: opts([["yes", "Yes"], ["no", "No"]]),
          persistence: p(INPUT, "answers.prospects.planning"),
        }),
        q({
          key: "prospects.preferences",
          label: "Expansion preferences",
          help: "For example proximity to customers, highway access or labour availability.",
          type: "textarea",
          width: "full",
          level: "B",
          visibleWhen: { all: [{ field: "prospects.planning", equals: "yes" }, { level: "B" }] },
          validation: { maxLength: 1000 },
          dimensions: ["site_feasibility"],
          persistence: p(INPUT, "answers.prospects.preferences"),
        }),
      ],
    },
    {
      key: "prospects",
      title: "Candidate sites",
      visibleWhen: { field: "prospects.planning", equals: "yes" },
      group: {
        key: "prospects",
        label: "Candidate sites",
        itemLabel: "Candidate",
        minItems: 1,
        maxItems: 8,
        level: "A",
        persistenceTable: "location_preferences",
        questions: [
          q({ key: "name", label: "Candidate name", type: "text", required: true, validation: { maxLength: 120 }, dimensions: ["site_feasibility"], persistence: p("location_preferences", "name") }),
          q({ key: "city", label: "City or town", type: "text", required: true, validation: { maxLength: 120 }, dimensions: ["site_feasibility"], persistence: p("location_preferences", "city") }),
          q({ key: "region", label: "State or region", type: "text", validation: { maxLength: 120 }, dimensions: ["site_feasibility"], persistence: p("location_preferences", "region") }),
          q({ key: "point", label: "Map position", help: "Optional until the site is short-listed. Hazard screening needs a confirmed position.", type: "geopoint", width: "full", dimensions: ["hazard_exposure", "site_feasibility"], persistence: p("location_preferences", "latitude, longitude, geocoder_name, match_quality, user_confirmed") }),
          q({ key: "intended_activity", label: "Intended use", type: "text", validation: { maxLength: 200 }, dimensions: ["site_feasibility"], persistence: p("location_preferences", "intended_activity") }),
          q({ key: "acquisition", label: "Acquisition route", type: "select", options: opts([["buy", "Buy"], ["lease", "Lease"], ["build", "Build on owned land"], ["undecided", "Undecided"]]), dimensions: ["site_feasibility"], persistence: p("location_preferences", "acquisition_preference") }),
          q({ key: "desired_area", label: "Area needed", type: "number", unit: "m²", validation: { min: 0, max: 100000000 }, dimensions: ["site_feasibility"], persistence: p("location_preferences", "desired_area") }),
          q({ key: "budget_amount", label: "Budget", help: "Leave blank if you have no figure. No market price is filled in.", type: "currency", sensitivity: "confidential", source: "user_assumption", validation: { min: 0 }, dimensions: ["site_feasibility", "financial_sensitivity"], persistence: p("location_preferences", "budget_amount") }),
          q({ key: "budget_currency", label: "Budget currency", type: "select", options: CURRENCIES, visibleWhen: { field: ".budget_amount", answered: true }, dimensions: ["site_feasibility"], persistence: p("location_preferences", "budget_currency") }),
          q({ key: "decision_date", label: "Target decision date", type: "date", dimensions: ["site_feasibility"], persistence: p("location_preferences", "decision_date") }),
          q({
            key: "utility_needs",
            label: "Utility needs",
            type: "multiselect",
            width: "full",
            options: opts([["three_phase_power", "Three-phase power"], ["piped_water", "Piped water"], ["high_water_volume", "High water volume"], ["cold_storage", "Cold storage"], ["fibre", "Fibre connectivity"], ["heavy_vehicle_access", "Heavy vehicle access"]]),
            dimensions: ["site_feasibility"],
            persistence: p("location_preferences", "utility_needs"),
          }),
          q({ key: "workforce", label: "Workforce needed", type: "number", validation: { integer: true, min: 0, max: 100000 }, dimensions: ["site_feasibility"], persistence: p("location_preferences", "workforce_requirements") }),
          q({ key: "weight_cost", label: "Weight: cost", help: "Cost, resilience and climate weights should total 100.", type: "percentage", unit: "%", source: "user_assumption", validation: { min: 0, max: 100 }, dimensions: ["site_feasibility"], persistence: p("location_preferences", "weights.cost") }),
          q({ key: "weight_resilience", label: "Weight: resilience", type: "percentage", unit: "%", source: "user_assumption", validation: { min: 0, max: 100 }, dimensions: ["site_feasibility"], persistence: p("location_preferences", "weights.resilience") }),
          q({ key: "weight_climate", label: "Weight: climate hazard", type: "percentage", unit: "%", source: "user_assumption", validation: { min: 0, max: 100 }, dimensions: ["site_feasibility"], persistence: p("location_preferences", "weights.climate") }),
          q({ key: "max_risk", label: "Highest acceptable hazard screen", type: "select", level: "B", visibleWhen: { level: "B" }, options: opts([["low", "Low only"], ["moderate", "Up to moderate"], ["any", "Any, if mitigated"]]), dimensions: ["site_feasibility"], persistence: p("location_preferences", "max_acceptable_risk") }),
        ],
      },
    },
  ],
};

export const operationsStep: StepDefinition = {
  id: "operations",
  number: 5,
  title: "Operational sensitivity and dependencies",
  short: "Operations",
  summary: "How strongly operations depend on power, water, cooling, connectivity, people and stock.",
  why: "These answers form the operational-sensitivity component. Unknown answers are excluded, not treated as low dependence.",
  dimensions: ["operational_sensitivity"],
  external: [],
  optional: false,
  sections: [
    {
      key: "ops.dependencies",
      title: "Dependencies",
      description: TRI_HELP,
      questions: [
        q({ key: "ops.electricity_dependency", label: "Electricity", type: "select", required: true, material: true, options: DEPENDENCY_LEVELS, dimensions: ["operational_sensitivity"], persistence: p("operational_profiles", "electricity_critical", "critical or high → yes; moderate or low → no; unsure → unknown. Level kept in details.") }),
        q({ key: "ops.water_dependency", label: "Water", type: "select", required: true, material: true, options: DEPENDENCY_LEVELS, dimensions: ["operational_sensitivity"], persistence: p("operational_profiles", "water_critical", "Same mapping as electricity.") }),
        q({ key: "ops.cooling_dependency", label: "Cooling or refrigeration", type: "select", required: true, material: true, options: DEPENDENCY_LEVELS, dimensions: ["operational_sensitivity"], persistence: p("operational_profiles", "cooling_critical", "Same mapping as electricity.") }),
        q({ key: "ops.telecom_dependency", label: "Telecoms and internet", type: "select", required: true, options: DEPENDENCY_LEVELS, dimensions: ["operational_sensitivity"], persistence: p("operational_profiles", "network_dependence") }),
        q({ key: "ops.transport_dependency", label: "Road access and transport", type: "select", required: true, options: DEPENDENCY_LEVELS, dimensions: ["operational_sensitivity"], persistence: p("operational_profiles", "transport_dependence") }),
        q({ key: "ops.perishable_inventory", label: "Do you hold perishable or temperature-sensitive stock?", type: "tristate", required: true, material: true, dimensions: ["operational_sensitivity"], persistence: p("operational_profiles", "perishable_inventory") }),
        q({ key: "ops.outdoor_work", label: "Does work happen outdoors or in unconditioned spaces?", type: "tristate", required: true, material: true, dimensions: ["operational_sensitivity", "hazard_exposure"], persistence: p("operational_profiles", "outdoor_workforce") }),
        q({ key: "ops.max_downtime_hours", label: "Longest stoppage the business can absorb", help: "Hours before losses become serious. Leave blank if unknown.", type: "number", unit: "hours", material: true, validation: { min: 0, max: 8760 }, dimensions: ["operational_sensitivity"], persistence: p("operational_profiles", "max_tolerable_downtime_hours") }),
        q({ key: "ops.workforce_commute", label: "How most staff reach work", type: "select", level: "B", visibleWhen: { level: "B" }, options: opts([["walk", "Walk or cycle"], ["public", "Public transport"], ["company", "Company transport"], ["own_vehicle", "Own vehicles"], ["mixed", "Mixed"]]), dimensions: ["operational_sensitivity"], persistence: p("operational_profiles", "details.workforce_commute") }),
        q({ key: "ops.inventory_days", label: "Stock normally held", type: "number", unit: "days", level: "B", visibleWhen: { level: "B" }, validation: { min: 0, max: 3650 }, dimensions: ["operational_sensitivity", "supply_chain"], persistence: p("operational_profiles", "inventory_characteristics") }),
        q({ key: "ops.critical_equipment", label: "Critical machinery or equipment", type: "textarea", width: "full", level: "B", visibleWhen: { level: "B" }, validation: { maxLength: 800 }, dimensions: ["operational_sensitivity"], persistence: p("operational_profiles", "machinery") }),
      ],
    },
    {
      key: "agri",
      title: "Agriculture",
      industries: ["agriculture"],
      questions: [
        q({ key: "agri.crops", label: "Main crops or livestock", type: "text", validation: { maxLength: 200 }, industries: ["agriculture"], dimensions: ["operational_sensitivity"], persistence: p("operational_profiles", "details.agri.crops") }),
        q({ key: "agri.irrigation", label: "Water source for crops or animals", type: "select", industries: ["agriculture"], options: opts([["rainfed", "Rain-fed only"], ["canal", "Canal or surface water"], ["groundwater", "Borewell or groundwater"], ["mixed", "Mixed"], ["unknown", "Not sure"]]), dimensions: ["operational_sensitivity", "hazard_exposure"], persistence: p("operational_profiles", "details.agri.irrigation") }),
        q({ key: "agri.growing_months", label: "Critical growing or production months", type: "multiselect", width: "full", industries: ["agriculture"], options: MONTHS, dimensions: ["operational_sensitivity"], persistence: p("operational_profiles", "seasonal_windows") }),
        q({ key: "agri.harvest_storage", label: "Harvest or produce storage", type: "select", industries: ["agriculture"], options: opts([["none", "Sold immediately"], ["open", "Open or covered yard"], ["warehouse", "Warehouse"], ["cold", "Cold storage"]]), dimensions: ["operational_sensitivity"], persistence: p("operational_profiles", "details.agri.harvest_storage") }),
      ],
    },
    {
      key: "mfg",
      title: "Manufacturing",
      industries: ["manufacturing"],
      questions: [
        q({ key: "mfg.process_cooling", label: "Does a process need cooling water or chilled air?", type: "tristate", industries: ["manufacturing"], dimensions: ["operational_sensitivity"], persistence: p("operational_profiles", "details.mfg.process_cooling") }),
        q({ key: "mfg.continuous_process", label: "Is any process continuous, so a stop spoils work in progress?", type: "tristate", industries: ["manufacturing"], dimensions: ["operational_sensitivity"], persistence: p("operational_profiles", "details.mfg.continuous_process") }),
        q({ key: "mfg.raw_material_storage", label: "Raw material storage", type: "select", industries: ["manufacturing"], options: opts([["indoor", "Indoors"], ["covered", "Outdoors, covered"], ["open", "Outdoors, open"], ["mixed", "Mixed"]]), dimensions: ["operational_sensitivity", "hazard_exposure"], persistence: p("operational_profiles", "details.mfg.raw_material_storage") }),
        q({ key: "mfg.equipment_temp_limit_c", label: "Ambient temperature above which equipment derates", type: "number", unit: "°C", level: "B", visibleWhen: { level: "B" }, industries: ["manufacturing"], validation: { min: 0, max: 80 }, dimensions: ["operational_sensitivity"], persistence: p("operational_profiles", "details.mfg.equipment_temp_limit_c") }),
      ],
    },
    {
      key: "cold",
      title: "Food, pharmaceutical and cold chain",
      industries: ["food_cold_chain"],
      questions: [
        q({ key: "cold.temperature_range", label: "Storage temperature", type: "select", industries: ["food_cold_chain"], options: opts([["frozen", "Frozen, below −15 °C"], ["chilled", "Chilled, 0–8 °C"], ["controlled", "Controlled ambient, 15–25 °C"], ["ambient", "Ambient, no control"]]), dimensions: ["operational_sensitivity"], persistence: p("operational_profiles", "refrigeration", "Frozen, chilled or controlled → yes; ambient → no.") }),
        q({ key: "cold.excursion_hours", label: "Hours stock can stay outside its range", type: "number", unit: "hours", industries: ["food_cold_chain"], validation: { min: 0, max: 720 }, dimensions: ["operational_sensitivity"], persistence: p("operational_profiles", "details.cold.excursion_hours") }),
        q({ key: "cold.backup_refrigeration", label: "Backup power or refrigeration for cold stock?", type: "tristate", industries: ["food_cold_chain"], dimensions: ["adaptive_capacity"], persistence: p("operational_profiles", "details.cold.backup_refrigeration") }),
        q({ key: "cold.temperature_logging", label: "Are storage temperatures logged?", type: "tristate", industries: ["food_cold_chain"], dimensions: ["adaptive_capacity"], persistence: p("operational_profiles", "details.cold.temperature_logging") }),
      ],
    },
    {
      key: "retail",
      title: "Retail and distribution",
      industries: ["retail"],
      questions: [
        q({ key: "retail.weather_footfall", label: "How much do heavy rain or heat reduce customer visits?", type: "select", industries: ["retail"], options: opts([["strong", "Strongly"], ["some", "Somewhat"], ["none", "Not noticeably"], ["unknown", "Not sure"]]), dimensions: ["operational_sensitivity", "financial_sensitivity"], persistence: p("operational_profiles", "details.retail.weather_footfall") }),
        q({ key: "retail.delivery_dependence", label: "Dependence on daily deliveries", type: "select", industries: ["retail"], options: DEPENDENCY_LEVELS, dimensions: ["supply_chain"], persistence: p("operational_profiles", "details.retail.delivery_dependence") }),
      ],
    },
    {
      key: "it",
      title: "IT and digital services",
      industries: ["it_services"],
      questions: [
        q({ key: "it.hosting", label: "Where core systems run", type: "select", industries: ["it_services"], options: opts([["on_premises", "On premises"], ["cloud", "Cloud"], ["hybrid", "Hybrid"]]), dimensions: ["operational_sensitivity"], persistence: p("operational_profiles", "details.it.hosting") }),
        q({ key: "it.ups_minutes", label: "UPS runtime for critical systems", type: "number", unit: "minutes", industries: ["it_services"], validation: { min: 0, max: 10000 }, dimensions: ["adaptive_capacity"], persistence: p("operational_profiles", "details.it.ups_minutes") }),
        q({ key: "it.redundant_connectivity", label: "Second internet link from a different provider?", type: "tristate", industries: ["it_services"], dimensions: ["adaptive_capacity"], persistence: p("operational_profiles", "details.it.redundant_connectivity") }),
        q({ key: "it.remote_share", label: "Share of work that can be done remotely", type: "percentage", unit: "%", industries: ["it_services"], validation: { min: 0, max: 100 }, dimensions: ["adaptive_capacity"], persistence: p("operational_profiles", "details.it.remote_share") }),
      ],
    },
    {
      key: "water",
      title: "Water-intensive operations",
      industries: ["water_intensive"],
      questions: [
        q({ key: "water.daily_use_m3", label: "Typical water use", type: "number", unit: "m³/day", industries: ["water_intensive"], validation: { min: 0, max: 1000000 }, dimensions: ["operational_sensitivity", "hazard_exposure"], persistence: p("operational_profiles", "details.water.daily_use_m3") }),
        q({ key: "water.sources", label: "Water sources", type: "multiselect", width: "full", industries: ["water_intensive"], options: opts([["municipal", "Municipal supply"], ["borewell", "Borewell"], ["tanker", "Tanker"], ["surface", "River, lake or canal"], ["recycled", "Recycled or harvested"]]), dimensions: ["operational_sensitivity"], persistence: p("operational_profiles", "details.water.sources") }),
        q({ key: "water.storage_days", label: "Days of water storage on site", type: "number", unit: "days", industries: ["water_intensive"], validation: { min: 0, max: 365 }, dimensions: ["adaptive_capacity"], persistence: p("operational_profiles", "details.water.storage_days") }),
        q({ key: "water.restrictions", label: "Have supply restrictions affected you before?", type: "tristate", industries: ["water_intensive"], dimensions: ["hazard_exposure"], persistence: p("operational_profiles", "details.water.restrictions") }),
      ],
    },
    {
      key: "outdoor",
      title: "Outdoor and heat-exposed work",
      industries: ["outdoor_work"],
      questions: [
        q({ key: "outdoor.share_pct", label: "Share of workforce working outdoors", type: "percentage", unit: "%", industries: ["outdoor_work"], validation: { min: 0, max: 100 }, dimensions: ["operational_sensitivity"], persistence: p("operational_profiles", "details.outdoor.share_pct") }),
        q({ key: "outdoor.shift_hours", label: "Can work hours be moved to cooler times?", type: "tristate", industries: ["outdoor_work"], dimensions: ["adaptive_capacity"], persistence: p("operational_profiles", "details.outdoor.shift_hours") }),
        q({ key: "outdoor.shade_rest", label: "Shade, water and rest breaks provided?", type: "tristate", industries: ["outdoor_work"], dimensions: ["adaptive_capacity"], persistence: p("operational_profiles", "details.outdoor.shade_rest") }),
      ],
    },
    {
      key: "assets",
      title: "Key assets",
      visibleWhen: { level: "B" },
      group: {
        key: "assets",
        label: "Key assets",
        itemLabel: "Asset",
        description: "Machinery, stock or buildings whose damage would stop operations.",
        minItems: 0,
        maxItems: 30,
        level: "B",
        persistenceTable: "business_assets",
        questions: [
          q({ key: "asset_type", label: "Asset type", type: "select", required: true, level: "B", options: opts([["machinery", "Machinery"], ["inventory", "Inventory"], ["building", "Building or fit-out"], ["vehicle", "Vehicle"], ["it_equipment", "IT equipment"], ["cold_storage", "Cold storage"], ["other", "Other"]]), dimensions: ["operational_sensitivity"], persistence: p("business_assets", "asset_type") }),
          q({ key: "description", label: "Description", type: "text", required: true, level: "B", validation: { maxLength: 200 }, dimensions: ["operational_sensitivity"], persistence: p("business_assets", "description") }),
          q({ key: "site", label: "Site", type: "site_ref", level: "B", dimensions: ["hazard_exposure"], persistence: p("business_assets", "location_id") }),
          q({ key: "replacement_value", label: "Replacement value", type: "currency", level: "B", sensitivity: "restricted_financial", validation: { min: 0 }, dimensions: ["financial_sensitivity"], persistence: p("business_assets", "replacement_value") }),
          q({ key: "currency", label: "Currency", type: "select", level: "B", options: CURRENCIES, visibleWhen: { field: ".replacement_value", answered: true }, dimensions: ["financial_sensitivity"], persistence: p("business_assets", "currency") }),
          q({ key: "value_basis", label: "Basis of value", type: "select", level: "B", visibleWhen: { field: ".replacement_value", answered: true }, options: opts([["invoice", "Purchase invoice"], ["insurance_valuation", "Insurance valuation"], ["quotation", "Replacement quotation"], ["estimate", "Own estimate"]]), dimensions: ["financial_sensitivity"], persistence: p("business_assets", "value_basis") }),
          q({ key: "below_ground_floor", label: "Kept at or below ground level?", type: "tristate", level: "B", dimensions: ["hazard_exposure"], persistence: p("business_assets", "at_or_below_ground") }),
          q({ key: "temperature_sensitive", label: "Temperature-sensitive?", type: "tristate", level: "B", dimensions: ["operational_sensitivity"], persistence: p("business_assets", "temperature_sensitive") }),
        ],
      },
    },
  ],
};
