import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { QUESTION_ENTRIES, STEPS } from "@/lib/questionnaire/registry";
import { DIMENSION_LABELS, TEMPLATE_KEY, TEMPLATE_VERSION, type QuestionDefinition } from "@/lib/questionnaire/types";

const SEED_PATH = "supabase/seed/question_definitions.sql";
const DICTIONARY_PATH = "metadata/DATA_DICTIONARY.md";
const BEGIN = "<!-- BEGIN:questionnaire (generated by scripts/export-questionnaire.ts) -->";
const END = "<!-- END:questionnaire -->";

const sqlText = (value: string | null | undefined) => (value === null || value === undefined ? "null" : `'${value.replace(/'/g, "''")}'`);
const sqlArray = (values: string[]) => `array[${values.map(sqlText).join(", ")}]::text[]`;
const cell = (value: string) => value.replace(/\|/g, "\\|").replace(/\n/g, " ");

function component(question: QuestionDefinition, groupKey: string | null): string {
  if (groupKey === "documents") return "UploadPanel";
  if (question.type === "geopoint") return "LocationField";
  if (question.type === "combobox" || question.type === "site_ref") return "Combobox";
  return `QuestionField (${question.type})`;
}

function seed(): string {
  const lines = [
    `-- Generated by scripts/export-questionnaire.ts from lib/questionnaire. Do not edit by hand.`,
    `-- Template ${TEMPLATE_KEY} ${TEMPLATE_VERSION}: ${STEPS.length} steps, ${QUESTION_ENTRIES.length} questions.`,
    "",
    `insert into public.assessment_templates (key, version, step_count, question_count)`,
    `values (${sqlText(TEMPLATE_KEY)}, ${sqlText(TEMPLATE_VERSION)}, ${STEPS.length}, ${QUESTION_ENTRIES.length})`,
    `on conflict (key, version) do update set step_count = excluded.step_count, question_count = excluded.question_count;`,
    "",
    `insert into public.question_definitions (template_key, template_version, question_path, step_id, step_number, label, question_type, unit, required, level, source_category, sensitivity, dimensions, persistence_table, persistence_column, material, display_order, definition) values`,
  ];
  const rows = QUESTION_ENTRIES.map(({ question, step, path }) => {
    const definition = JSON.stringify({ ...question, path });
    return `  (${[
      sqlText(TEMPLATE_KEY),
      sqlText(TEMPLATE_VERSION),
      sqlText(path),
      sqlText(step.id),
      step.number,
      sqlText(question.label),
      sqlText(question.type),
      sqlText(question.unit),
      question.required,
      sqlText(question.level),
      sqlText(question.source),
      sqlText(question.sensitivity),
      sqlArray(question.dimensions),
      sqlText(question.persistence.table),
      sqlText(question.persistence.column),
      question.material,
      question.order,
      `${sqlText(definition)}::jsonb`,
    ].join(", ")})`;
  });
  lines.push(rows.join(",\n"));
  lines.push(
    `on conflict (template_key, template_version, question_path) do update set`,
    `  step_id = excluded.step_id, step_number = excluded.step_number, label = excluded.label, question_type = excluded.question_type,`,
    `  unit = excluded.unit, required = excluded.required, level = excluded.level, source_category = excluded.source_category,`,
    `  sensitivity = excluded.sensitivity, dimensions = excluded.dimensions, persistence_table = excluded.persistence_table,`,
    `  persistence_column = excluded.persistence_column, material = excluded.material, display_order = excluded.display_order,`,
    `  definition = excluded.definition;`,
    "",
  );
  return lines.join("\n");
}

function dictionary(): string {
  const out = [
    BEGIN,
    "",
    `## Business assessment questions (${TEMPLATE_KEY} ${TEMPLATE_VERSION})`,
    "",
    `${QUESTION_ENTRIES.length} questions across ${STEPS.length} steps. Paths with \`[]\` are fields of a repeated row. Geopoint fields are stored as \`<key>_lat\`, \`<key>_lon\`, \`<key>_source\`, \`<key>_match\` and \`<key>_confirmation\` in the answers and as latitude, longitude, geocoder name, match quality and user confirmation in the database.`,
    "",
    "Level A questions are shown to everyone; Level B only when the advanced assessment is chosen. `restricted_financial` answers are stored in `assessment_input_financials` and `financial_profiles`, readable by owner, admin and analyst roles only.",
  ];
  for (const step of STEPS) {
    out.push("", `### ${step.number}. ${step.title}`, "", "| Path | Label | Type / unit | Req. | Level | Source | Sensitivity | Dimensions | Database target | Component |", "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |");
    for (const { question, path, group } of QUESTION_ENTRIES.filter((entry) => entry.step.id === step.id)) {
      const target = `\`${question.persistence.table}.${question.persistence.column}\`${question.persistence.note ? ` (${question.persistence.note})` : ""}`;
      out.push(
        `| \`${path}\` | ${cell(question.label)} | ${question.type}${question.unit ? ` (${question.unit})` : ""} | ${question.required ? "Yes" : ""} | ${question.level} | ${question.source} | ${question.sensitivity} | ${question.dimensions.map((dimension) => DIMENSION_LABELS[dimension]).join(", ")} | ${cell(target)} | ${component(question, group?.key ?? null)} |`,
      );
    }
  }
  out.push("", END);
  return out.join("\n");
}

mkdirSync("supabase/seed", { recursive: true });
writeFileSync(SEED_PATH, seed(), "utf8");

const existing = readFileSync(DICTIONARY_PATH, "utf8");
const section = dictionary();
const start = existing.indexOf(BEGIN);
const end = existing.indexOf(END);
const next = start >= 0 && end > start ? `${existing.slice(0, start)}${section}${existing.slice(end + END.length)}` : `${existing.trimEnd()}\n\n${section}\n`;
writeFileSync(DICTIONARY_PATH, next, "utf8");

console.log(`Wrote ${SEED_PATH} and updated ${DICTIONARY_PATH}: ${STEPS.length} steps, ${QUESTION_ENTRIES.length} questions.`);
